version: '3'
services:
  api:
    image: ivorobioff/complex-server
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
  client:
    image: ivorobioff/complex-client
  worker:
    image: ivorobioff/complex-worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  nginx:
    image: ivorobioff/complex-nginx
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - client
      - api

